Repository gwdetchar/gwdetchar, pull requests merged in 2018-10, with the labels that each got.

#152 Reduce the data duration read in from frames
  bin/gwdetchar-omega
Labels: enhancement

#158 Allow Omega scan input to be read from a local cache
  bin/gwdetchar-omega
Labels: enhancement, feature-request

#160 Refresh omega scans until they finish
  bin/gwdetchar-omega
  gwdetchar/omega/html.py
Labels: enhancement

#161 Patched gwdetchar-overflow
  bin/gwdetchar-overflow
Labels: bug

#162 Omega scan enhancements improving mobile display
  gwdetchar/omega/html.py
  share/sass/gwdetchar-omega.scss
Labels: enhancement

#169 Add links to the simulink models from overflow summary pages
  bin/gwdetchar-overflow
Labels: feature-request

#155 Support omega scan sub-blocks
  bin/gwdetchar-omega
  gwdetchar/omega/html.py
Labels: enhancement, feature-request

#172 Navigation enhancements for gwdetchar-omega
  gwdetchar/omega/html.py
  share/sass/gwdetchar-omega.scss
Labels: enhancement

#173 Use absolute https URLs for HTML resources
  gwdetchar/io/html.py
  gwdetchar/omega/html.py
Labels: enhancement

#178 Cleaning up omega scan command line options
  bin/gwdetchar-omega
  gwdetchar/cli.py
Labels: bug, enhancement

#176 Allow users to require state flags to be active to process omega scans
  bin/gwdetchar-omega
  gwdetchar/omega/html.py
Labels: enhancement, feature-request

#183 Omega scan config documentation
  bin/gwdetchar-omega
  gwdetchar/omega/config.py
  gwdetchar/omega/html.py
Labels: enhancement, feature-request

#187 Handle the mapping of LIMITS to LIMENS/SWSTATS more gracefully
  bin/gwdetchar-software-saturations
Labels: bug, enhancement, feature-request
