Repository gwdetchar/gwdetchar, pull requests merged in 2018-09, with the labels that each got.

#126 Reduce default false alarm rate threshold to 1e-10 Hz
  bin/gwdetchar-omega
Labels: feature-request

#129 In omega scans: convert data to float64, use linear detrending
  bin/gwdetchar-omega
Labels: enhancement, feature-request

#123 Misc. formatting improvements for gwdetchar-omega
  bin/gwdetchar-omega
  gwdetchar/omega/html.py
  gwdetchar/omega/plot.py
  share/sass/gwdetchar-omega.scss
Labels: enhancement

#142 Adjust the size of Q-transform spectrograms
  bin/gwdetchar-omega
Labels: enhancement

#145 Support for multi-IFO omega scans
  bin/gwdetchar-omega
  gwdetchar/omega/html.py
Labels: enhancement, feature-request

#118 Update to gwpy-0.12
  bin/gwdetchar-overflow
  bin/gwdetchar-scattering
  bin/gwdetchar-software-saturations
  gwdetchar/io/html.py
  gwdetchar/omega/html.py
  gwdetchar/omega/plot.py
  requirements.txt
  setup.py
Labels: upstream:gwpy

#134 Improvements to gwdetchar-lasso-correlation and gwpy-0.12.0 compatibility
  bin/gwdetchar-lasso-correlation
  gwdetchar/lasso.py
Labels: upstream:gwpy

#147 Omega scan output summary tables
  gwdetchar/omega/html.py
Labels: enhancement, feature-request
