Repository gwdetchar/gwdetchar, pull requests merged in 2019-02, with the labels that each got.

#216 Render channel names in a code-like font
  gwdetchar/omega/plot.py
Labels: enhancement

#217 Resolve a longstanding issue with wdq-batch input files that contain only one event time
  bin/wdq-batch
Labels: bug

#206 Reduce memory usage in Q-transform spectrogram plots
  bin/gwdetchar-omega
  bin/wdq-batch
  gwdetchar/omega/plot.py
  gwdetchar/tests/test_daq.py
  gwdetchar/tests/test_io_ligolw.py
  gwdetchar/tests/test_saturation.py
  requirements.txt
  setup.py
Labels: enhancement

#189 Cross-correlate Omega scan channels
  bin/gwdetchar-omega
  bin/wdq
  bin/wdq-batch
  gwdetchar/omega/__init__.py
  gwdetchar/omega/config.py
  gwdetchar/omega/core.py
  gwdetchar/omega/html.py
  gwdetchar/omega/matlab.py
  gwdetchar/omega/plot.py
Labels: enhancement, feature-request

#218 Matlab Omega deprecation: phase two
  bin/wdq
  bin/wdq-batch
Labels: enhancement

#222 Use gwdatafind for data access
  bin/gwdetchar-mct
  bin/gwdetchar-overflow
  bin/gwdetchar-software-saturations
  gwdetchar/daq.py
  gwdetchar/io/datafind.py
  gwdetchar/tests/test_daq.py
  requirements.txt
  setup.py
Labels: enhancement

#223 Fixed some labelling issues when not using TeX with matplotlib
  bin/gwdetchar-overflow
  bin/gwdetchar-scattering
  bin/gwdetchar-software-saturations
Labels: bug

#220 Reproduce GWPY_TEX_RCPARAMS for use with gwpy-0.13+
  bin/gwdetchar-lasso-correlation
  bin/gwdetchar-mct
  bin/gwdetchar-overflow
  bin/gwdetchar-scattering
  bin/gwdetchar-slow-correlation
  bin/gwdetchar-software-saturations
  gwdetchar/misc.py
Labels: upstream:gwpy

#224 Fixed bug in gwdetchar-scattering introduced by #223
  bin/gwdetchar-scattering
Labels: bug

#225 Bug fixes and formatting enhancements for gwdetchar-omega
  bin/gwdetchar-omega
  gwdetchar/io/datafind.py
  gwdetchar/omega/config.py
  gwdetchar/omega/core.py
  gwdetchar/omega/html.py
  gwdetchar/omega/plot.py
Labels: bug, enhancement

#226 Use urlparse to expedite frame reading
  bin/gwdetchar-omega
  gwdetchar/io/datafind.py
Labels: enhancement

#228 Python 3 compliance for a map object in wdq-batch
  bin/wdq-batch
Labels: bug

#229 wdq-batch: use pycondor instead of glue.pipeline
  .travis.yml
  bin/wdq-batch
  requirements.txt
  setup.py
Labels: enhancement

#230 Deprecate support for Matlab omega scans
  bin/gwdetchar-omega-batch
  bin/wdq
  bin/wdq-batch
  gwdetchar/omega/__init__.py
  gwdetchar/omega/matlab.py
  requirements.txt
  setup.py
Labels: enhancement

#234 Extensive omega scan unit tests
  gwdetchar/omega/config.py
  gwdetchar/omega/core.py
  gwdetchar/omega/html.py
  gwdetchar/omega/plot.py
  gwdetchar/omega/tests/__init__.py
  gwdetchar/omega/tests/test_config.py
  gwdetchar/omega/tests/test_core.py
  gwdetchar/omega/tests/test_html.py
  gwdetchar/omega/tests/test_plot.py
Labels: enhancement, omega scans

#233 Use TeX only if it's available
  gwdetchar/misc.py
Labels: enhancement

#236 More unit tests to increase coverage and support python 3.7
  .travis.yml
  gwdetchar/io/html.py
  gwdetchar/io/tests/__init__.py
  gwdetchar/io/tests/test_datafind.py
  gwdetchar/io/tests/test_html.py
  gwdetchar/io/tests/test_ligolw.py
  gwdetchar/omega/html.py
  gwdetchar/omega/tests/test_config.py
  gwdetchar/omega/tests/test_html.py
  gwdetchar/omega/tests/test_plot.py
  gwdetchar/utils.py
Labels: enhancement, omega scans

#235 Omega scan spectral density estimation
  bin/gwdetchar-omega
  gwdetchar/io/datafind.py
  gwdetchar/omega/core.py
  requirements.txt
  setup.py
Labels: enhancement, omega scans, upstream:gwpy
